title: Cricket's Shorthand Website
author: Cricket
description: Things I often tell others about shorthand, especially Orthic.
markdown: kramdown
url: https://cricketbr.github.io/Crickets-Shorthand-Site
baseurl: /


#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
