title: Cricket's Shorthand Website
author: Cricket
description: Useful Shorthand-Related Stuff.
markdown: kramdown
kramdown: 
  toc_levels: 2..6
  syntax_highlighter: rouge
url: https://cricketbr.github.io/Crickets-Shorthand-Site
baseurl: /


#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
